### ISSUE TITLE
Permission errrors while building JDG image

### ISSUE THREAD

**Issue by rimolive** [tqvarnst/docker-images#5]
I followed the instructions to build a JDG Docker Image and I got the following error:

``` bash
Step 10 : RUN /usr/bin/unzip -q $HOME/jboss-datagrid-6.5.0-server.zip -d $HOME
 ---> Running in bb245414a108
error:  cannot open zipfile [ /home/jdg/jboss-datagrid-6.5.0-server.zip ]
        Permission denied
unzip:  cannot find or open /home/jdg/jboss-datagrid-6.5.0-server.zip, /home/jdg/jboss-datagrid-6.5.0-server.zip.zip or /home/jdg/jboss-datagrid-6.5.0-server.zip.ZIP.
INFO[0087] The command [/bin/sh -c /usr/bin/unzip -q $HOME/jboss-datagrid-6.5.0-server.zip -d $HOME] returned a non-zero code: 9 
```

Is there something I'm missing or it should be really treated as a bug?

**Comment by tqvarnst** [comment]
Sorry for the late reply, these docker images are more for my own usage and are not 100% documented and I only update them to latest version when I have time over. However feel free to use them. I noticed that you updated the it to us JDG 6.5.0. Did you also update the ADD step in the Dockerfile? It's either that it cannot find the file or a weird permission issue. If you provide your Dockerfile I can help more, but since this issue is really old I'm going to close it. Let me know if you still have issues and I will try to help.

Cheers
Thomas
